# Generated by Django 4.2.7 on 2023-11-27 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_estudiante', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('año', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tiene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante_id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos.estudiante')),
                ('profesor_id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos.profesor')),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grupo_año',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos.grupo'),
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('nombre', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('semestre', models.CharField(max_length=255)),
                ('nota', models.CharField(max_length=255)),
                ('profesor_id_profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos.profesor')),
            ],
        ),
    ]
