# Generated by Django 4.1.4 on 2023-11-27 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Grupos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='nota',
        ),
        migrations.CreateModel(
            name='Asignatura_Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(max_length=255)),
                ('asignatura_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos.asignatura')),
                ('estudiante_id_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Grupos.estudiante')),
            ],
        ),
    ]
